lbs:
  centos:
    '7':
      repos: ['http://download.solidcharity.com/repos/tpokorra/nsis/centos/7/lbs-tpokorra-nsis.repo', 'epel-release', 'epel-testing', 'https://copr.fedorainfracloud.org/coprs/tpokorra/mono-5.14/repo/epel-7/tpokorra-mono-5.14-epel-7.repo']
