lbs:
  fedora:
    '21':
      repos: ['https://download.solidcharity.com/repos/tpokorra/nant/fedora/21/lbs-tpokorra-nant.repo']
  centos:
    '6':
      repos: ['http://lbs.solidcharity.com/repos/tpokorra/mono/centos/6/lbs-tpokorra-mono.repo', 'http://download.lbs.solidcharity.com/repos/tpokorra/nsis/centos/6/lbs-tpokorra-nsis.repo', 'epel-release']
    '7':
      repos: ['http://download.mono-project.com/repo/centos/', 'http://download.lbs.solidcharity.com/repos/tpokorra/nsis/centos/7/lbs-tpokorra-nsis.repo', 'http://download.lbs.solidcharity.com/repos/tpokorra/nant/centos/7/lbs-tpokorra-nant.repo', 'https://download.solidcharity.com/repos/tpokorra/openpetra/centos/7/lbs-tpokorra-openpetra.repo', 'epel-release']
