lbs:
  source:
    download: 
      base.yml.gz: "https://github.com/openpetra/demo-databases/raw/master/base.yml.gz"
      plugin_bankimport.tar.gz: "https://github.com/SolidCharity/OpenPetraPlugin_Bankimport/archive/master.tar.gz"
      plugin_bankimport_csv.tar.gz: "https://github.com/SolidCharity/OpenPetraPlugin_BankimportCSV/archive/master.tar.gz"
      plugin_bankimport_mt940.tar.gz: "https://github.com/SolidCharity/OpenPetraPlugin_BankimportMT940/archive/master.tar.gz"
