lbs:
  source:
    download: 
      base.yml.gz: "https://github.com/openpetra/demo-databases/raw/master/base.yml.gz"
      clean.yml.gz: "https://github.com/openpetra/demo-databases/raw/master/clean.yml.gz"
